version: "3"
services:
  collector:
    build: .
    env_file:
      - .env
    ports:
      - "${COLLECTOR_PORT}:${COLLECTOR_PORT}"

  agent:
    image: grafana/agent:latest
    volumes:
      - ./agent/config:/etc/agent-config
    environment:
      GRAFANA_JOB_NAME: "local/${NETWORK}"
    env_file:
      - .env
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -config.expand-env=true
      - -server.http.address=0.0.0.0:12345
    ports:
      - 12345:12345
    depends_on:
      - collector
