version: "3"
services:
  collector:
    image: 578642810119.dkr.ecr.us-east-1.amazonaws.com/xbacked-collector
    env_file:
      - .env
    ports:
      - "${COLLECTOR_PORT}:${COLLECTOR_PORT}"

  agent:
    image: grafana/agent:latest
    environment:
      GRAFANA_JOB_NAME: "collector/prod"
    env_file:
      - .env
    entrypoint:
      - /bin/agent
      - -metrics.wal-directory=/tmp/grafana-agent-wal
      - -enable-features=remote-configs
      - -config.file=https://xbacked-collector-agent-config.s3.amazonaws.com/agent.yaml
      - -config.expand-env=true
    ports:
      - "${AGENT_PORT}:${AGENT_PORT}"
    depends_on:
      - collector
