metrics:
  global:
    scrape_interval: 60s
  configs:
  - name: hosted-prometheus
    scrape_configs:
      - job_name: ${GRAFANA_JOB_NAME}
        static_configs:
        - targets: [${COLLECTOR_HOST}]
    remote_write:
      - url: https://${GRAFANA_PROM_HOST}/api/prom/push
        basic_auth:
          username: ${GRAFANA_PROM_USER}
          password: ${GRAFANA_PASS}