export const cleanEnv = (env: any) => {
    return {
        ALERT_GRAFANA_COOLDOWN: env.ALERT_GRAFANA_COOLDOWN,
        ALERT_VAULT_READ_COOLDOWN: env.ALERT_VAULT_READ_COOLDOWN,
        ALERT_TVL_COLLECTION_COOLDOWN: env.ALERT_TVL_COLLECTION_COOLDOWN,
        ALERT_ORACLE_BALANCE_COOLDOWN: env.ALERT_ORACLE_BALANCE_COOLDOWN,
        LOW_ORACLE_BALANCE: env.LOW_ORACLE_BALANCE,
        ALERT_ORACLE_THRESHOLD: env.ALERT_ORACLE_THRESHOLD,
        ALERT_ORACLE_COOLDOWN: env.ALERT_ORACLE_COOLDOWN,
        ALERT_REDEMPTION_THRESHOLD: env.ALERT_REDEMPTION_THRESHOLD,
        ALERT_REDEMPTION_COOLDOWN: env.ALERT_REDEMPTION_COOLDOWN
    }
}